# This is a basic Azure DevOps pipeline to validate Terraform

name: ' Validate Terraform code: '

variables:
  - group: 'TerraformProdDeploy'

# We disable builds for any commits as everything should go through pull requests
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    # We want to handle only changes relevant for this pipeline
    include:
    - environments/manual-approve-with-azure-devops/
    - modules/databricks-department-clusters/
    exclude:
    - environments/manual-approve-with-azure-devops/README.md
    - environments/manual-approve-with-github-actions/
    - modules/databricks-department-clusters/README.md
    
pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'
  displayName: 'Install Terraform'

- script: |
    terraform fmt -check
  displayName: 'Check formatting of Terraform code'
  workingDirectory: environments/manual-approve-with-azure-devops/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform init'
  inputs:
    command: 'init'
    commandOptions: '-input=false -no-color'
    backendType: 'azurerm'
    backendServiceArm: $(SERVICE_CONNECTION_NAME)
    backendAzureRmResourceGroupName: $(BACKEND_RG_NAME)
    backendAzureRmStorageAccountName: $(BACKEND_SA_NAME)
    backendAzureRmContainerName: $(BACKEND_CONTAINER_NAME)
    backendAzureRmKey: $(BACKEND_KEY)
    allowTelemetryCollection: false
    workingDirectory: environments/manual-approve-with-azure-devops/

- task: TerraformCLI@0
  displayName: 'Terraform validate'
  inputs:
    command: 'validate'
    commandOptions: '-no-color'
    environmentServiceName: $(SERVICE_CONNECTION_NAME)
    allowTelemetryCollection: false
    workingDirectory: environments/manual-approve-with-azure-devops/

- script: |
    env|sort
  displayName: 'get debugging information'
  workingDirectory: environments/manual-approve-with-azure-devops/
  enabled: 'true'
    
- task: TerraformCLI@0
  displayName: 'Terraform plan'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
  inputs:
    command: 'plan'
    commandOptions: '-lock=false -input=false -no-color'
    environmentServiceName: $(SERVICE_CONNECTION_NAME)
    allowTelemetryCollection: false
    workingDirectory: environments/manual-approve-with-azure-devops/
